---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: feng
  labels:
    app: redis
spec:
  selector:
    app: redis
  ports:
    - name: http
      protocol: TCP
      port: 6379
      targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: feng
  labels:
    app: redis
spec:
  selector:
    matchLabels:
      app: redis
  revisionHistoryLimit: 5
  replicas: 1
  progressDeadlineSeconds: 60
  template:
    metadata:
      labels:
        app: redis
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: redis
          image: redis:6.2.6
          imagePullPolicy: IfNotPresent
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
          command:
            - redis-server
            - "/redis/redis.conf"
          resources:
            limits:
              memory: 128Mi
              cpu: '1'
          envFrom:
            - configMapRef:
                name: env
            - secretRef:
                name: env-secret
          volumeMounts:
            - name: data
              mountPath: /data
            - name: config
              mountPath: /redis
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: redis-data
        - name: config
          configMap:
            name: redis-conf
            items:
              - key: redis-conf
                path: redis.conf

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-conf
  namespace: feng
data:
  redis-conf: |
    protected-mode no
    maxmemory-policy allkeys-lru
    save 3600 1
    save 300 100
    save 60 10000
    requirepass 9RhbxfQaHo8cs2gE
    maxmemory 64mb
    maxmemory-policy volatile-lru
    appendonly yes


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
  namespace: feng
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  # 申领可以通过为 storageClassName 属性设置 StorageClass 的名称来请求特定的存储类。
  # 只有所请求的类的 PV 卷，即 storageClassName 值与 PVC 设置相同的 PV 卷，
  # 才能绑定到 PVC 申领。
  storageClassName: gluster-storageclass
