apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: feng
  labels:
    app: gateway
spec:
  type: NodePort
  selector:
    app: gateway
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30800
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: feng
  labels:
    app: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  revisionHistoryLimit: 10
  replicas: 1
  progressDeadlineSeconds: 300
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: gateway
        octopusexport: OctopusExport
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: gateway
          image: registry.cn-hangzhou.aliyuncs.com/f-boot/gateway:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: gateway
              containerPort: 8000
              protocol: TCP
          resources:
            limits:
              memory: 1024Mi
              cpu: '1'
          env:
            - name: PROFILE
              value: prod
            # 指定时区
            - name: TZ
              value: Asia/Shanghai
            - name: NACOS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: nacos
                  key: username
            - name: NACOS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nacos
                  key: password
            - name: NACOS_SERVER_ADDR
              valueFrom:
                configMapKeyRef:
                  name: nacos
                  key: serverAddr
            - name: NACOS_NAMESPACE
              valueFrom:
                configMapKeyRef:
                  name: nacos
                  key: namespace
            - name: NACOS_GROUP
              valueFrom:
                configMapKeyRef:
                  name: nacos
                  key: group
          volumeMounts:
            - name: gateway-log
              mountPath: ./logs
      volumes:
        - name: gateway-log
          persistentVolumeClaim:
            claimName: gateway-log