---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: feng
  labels:
    app: gateway
spec:
  type: NodePort
  selector:
    app: gateway
  ports:
    - name: http
      protocol: TCP
      # 默认情况下，为了方便起见，`targetPort` 被设置为与 `port` 字段相同的值。
      port: 8000
      targetPort: 8000
      # 默认情况下，为了方便起见，Kubernetes 控制平面会从某个范围内分配一个端口号（默认：30000-32767）
      nodePort: 30800
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: feng
  labels:
    app: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  # deploy 升级最大记录数由 revisionHistoryLimit 定义，默认值为 10。
  revisionHistoryLimit: 10
  replicas: 1
  # deploy 升级过程中的最大时间由 progressDeadlineSeconds 来定义。
  # 如果升级过程被暂停了，该时间也会同步暂停，时间不会一直增长。
  progressDeadlineSeconds: 300
  strategy:
    type: RollingUpdate
    rollingUpdate:
      # 和期望ready的副本数比，不可用副本数最大比例（或最大值），这个值越小，越能保证服务稳定，更新越平滑；
      maxUnavailable: 0
      # 和期望ready的副本数比，超过期望副本数最大比例（或最大值），这个值调的越大，副本更新速度越快。
      maxSurge: 1
  template:
    metadata:
      labels:
        app: gateway
    spec:
      # 可以定义优雅关闭的宽限期，即在收到停止请求后，
      # 有多少时间来进行资源释放或者做其它操作，如果到了最大时间还没有停止，会被强制结束。
      terminationGracePeriodSeconds: 30
      containers:
        - name: gateway
          image: registry.cn-hangzhou.aliyuncs.com/f-boot/gateway:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: gateway
              containerPort: 8000
              protocol: TCP
          resources:
            limits:
              memory: 1024Mi
              cpu: '1'
          envFrom:
            - configMapRef:
                name: boot-env
            - secretRef:
                name: boot-secret
          volumeMounts:
            - name: gateway-log
              mountPath: /logs
      volumes:
        - name: gateway-log
          persistentVolumeClaim:
            claimName: gateway-log
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gateway-log
  namespace: feng
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: nfs-storage