#server:
#  port: 8080
#
## Spring
#spring:
#  cloud:
#    nacos:
#      discovery:
#        # 服务注册地址
#        server-addr: 127.0.0.1:8848
#        # 命名空间
#        namesapce: dev

#f:
#  gateway:
#    notAuthUris:
#      - /order/login
#      - /order/getKey

#spring:
#  cloud:
#    gateway:
#      routes:
#        # 订单
#        - id: order
#          uri: lb://order
#          predicates:
#            - Path=/order/**
#          filters:
#            - StripPrefix=1
#        # 系统模块
#        - id: sys
#          uri: lb://sys
#          predicates:
#            - Path=/sys/**
#          filters:
#            - StripPrefix=1
#        # 文件服务
#        - id: file
#          uri: lb://file
#          predicates:
#            - Path=/file/**
#          filters:
#            - StripPrefix=1
#        # 支付服务
#        - id: pay
#          uri: lb://pay
#          predicates:
#            - Path=/pay/**
#          filters:
#            - StripPrefix=1
#        # 文件服务
#        - id: message
#          uri: lb://message
#          predicates:
#            - Path=/file/**
#          filters:
#            - StripPrefix=1


