#server:
#  port: 8080
#  # 启用压缩
#  compression:
#    enabled: true
#    mime-types: application/json
#  http2:
#    enabled: true
#  # 优雅关机
#  shutdown: graceful
#
## Spring
#spring:
#  cloud:
#    nacos:
#      discovery:
#        username: nacos
#        password: nacos
#        server-addr: 127.0.0.1:8848
#        namespace: dev
#    gateway:
#      discovery:
#        locator:
#          lowerCaseServiceId: true
#          enabled: true
#f:
#  gateway:
#    name: dev
#    notAuthUris:
#      - /auth/login
#      - /auth/getKey
#      - /sys/app/version

#spring:
#  cloud:
#    loadbalancer:
#      cache:
#        enabled: true
#        ttl: 5s
#        capacity: 512

#spring:
#  cloud:
#    gateway:
#      httpclient:
#        connect-timeout: 10000
#        response-timeout: 5s

#spring:
#  cloud:
#    inetutils:
#      preferredNetworks:
#        - 192.168