version : '3.9'
services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - feng
    restart: always
    volumes:
      - /home/feng/minio/disk1:/disk1
      - /home/feng/minio/disk2:/disk2
      - /home/feng/minio/disk3:/disk3
      - /home/feng/minio/disk4:/disk4
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
    environment:
      - MINIO_ROOT_USER=feng
      - MINIO_ROOT_PASSWORD=F6yXaV4ZbuIPACgprUQ38jEw9nKhWNJo
    command: server /disk{1...4} --console-address ":9001"
  redis:
    image: redis:6.2.6
    ports:
      - "16379:6379"
    networks:
      - feng
    restart: always
    volumes:
      - /home/feng/redis/data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    entrypoint: [
        "redis-server",
        "/usr/local/etc/redis/redis.conf",
    ]
  nacos:
    image: nacos/nacos-server:v2.0.4
    ports:
      - "8848:8848"
    networks:
      - feng
    restart: always
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
    env_file:
      - ./nacos_server.env
  sentinel:
    image: bladex/sentinel-dashboard:1.8.0
    ports:
      - "8858:8858"
    networks:
      - feng
    entrypoint: [
        "java",
        "-server",
        "-Djava.security.egd=file:/dev/./urandom",
        "-Dserver.port=8858",
        "-Dcsp.sentinel.api.port=8719",
        "-Dcsp.sentinel.dashboard.server=localhost:8858",
        "-Dproject.name=sentinel-dashboard",
        "-Dsentinel.dashboard.auth.username=feng",
        "-Dsentinel.dashboard.auth.password=feng",
        "-jar",
        "app.jar"
    ]
    restart: always
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
    depends_on:
      - nacos
  gateway:
    image: registry.cn-hangzhou.aliyuncs.com/f-boot/gateway:1.0.0
    ports:
      - "8000:8000"
    depends_on:
      - sentinel
      - redis
    networks:
      - feng
    restart: always
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
    env_file:
      - ./cloud_nacos.env
  sys:
    image: registry.cn-hangzhou.aliyuncs.com/f-boot/sys-service:1.0.0
    ports:
      - "18080"
    depends_on:
      - sentinel
      - redis
    networks:
      - feng
    restart: always
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
    env_file:
      - ./cloud_nacos.env
  message:
    image: registry.cn-hangzhou.aliyuncs.com/f-boot/message-service:1.0.0
    ports:
      - "18081"
    depends_on:
      - sentinel
      - redis
    networks:
      - feng
    restart: always
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
    env_file:
      - ./cloud_nacos.env
  file:
    image: registry.cn-hangzhou.aliyuncs.com/f-boot/file-service:1.0.0
    ports:
      - "18082"
    depends_on:
      - sentinel
      - redis
      - minio
    networks:
      - feng
    restart: always
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
    env_file:
      - ./cloud_nacos.env
networks:
  feng: