version : '3.9'
services:
  sentinel:
    image: bladex/sentinel-dashboard:1.8.0
    ports:
      - "8858:8858"
    networks:
      - feng
    entrypoint: [
        "java",
        "-server",
        "-Djava.security.egd=file:/dev/./urandom",
        "-Dserver.port=8858",
        "-Dcsp.sentinel.api.port=8719",
        "-Dcsp.sentinel.dashboard.server=localhost:8858",
        "-Dproject.name=sentinel-dashboard",
        "-Dsentinel.dashboard.auth.username=feng",
        "-Dsentinel.dashboard.auth.password=feng",
        "-jar",
        "app.jar"
    ]
  gateway:
    image: registry.cn-hangzhou.aliyuncs.com/f-boot/gateway:1.0.0
    ports:
      - "8000:8000"
    depends_on:
      - sentinel
    networks:
      - feng
    restart: always
  sys:
    image: registry.cn-hangzhou.aliyuncs.com/f-boot/sys-service:1.0.0
    ports:
      - "18080"
    depends_on:
      - sentinel
    networks:
      - feng
    restart: always
  message:
    image: registry.cn-hangzhou.aliyuncs.com/f-boot/message-service:1.0.0
    ports:
      - "18081"
    depends_on:
      - sentinel
    networks:
      - feng
    restart: always

networks:
  feng: