---
apiVersion: v1
kind: Service
metadata:
  name: file
  namespace: feng
  labels:
    app: file
spec:
  selector:
    app: file
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: file
  namespace: feng
  labels:
    app: file
spec:
  selector:
    matchLabels:
      app: file
  revisionHistoryLimit: 10
  replicas: 1
  progressDeadlineSeconds: 300
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: file
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: file
          image: registry.cn-hangzhou.aliyuncs.com/f-boot/file:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: file
              containerPort: 18082
              protocol: TCP
          resources:
            limits:
              memory: 512Mi
              cpu: '1'
          env:
            - name: PROFILE
              value: pro
            # 指定时区
            - name: TZ
              value: Asia/Shanghai
            - name: NACOS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: nacos
                  key: username
            - name: NACOS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nacos
                  key: password
            - name: NACOS_SERVER_ADDR
              valueFrom:
                configMapKeyRef:
                  name: nacos
                  key: serverAddr
            - name: NACOS_NAMESPACE
              valueFrom:
                configMapKeyRef:
                  name: nacos
                  key: namespace
            - name: NACOS_GROUP
              valueFrom:
                configMapKeyRef:
                  name: nacos
                  key: group
          volumeMounts:
            - name: file-log
              mountPath: /logs
      volumes:
        - name: file-log
          persistentVolumeClaim:
            claimName: file-log

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: file-log
  namespace: feng
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-storage