---
apiVersion: v1
kind: Service
metadata:
  name: order
  namespace: feng
  labels:
    app: order
spec:
  selector:
    app: order
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  namespace: feng
  labels:
    app: order
spec:
  selector:
    matchLabels:
      app: order
  revisionHistoryLimit: 10
  replicas: 1
  progressDeadlineSeconds: 300
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: order
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: order
          image: registry.cn-hangzhou.aliyuncs.com/f-boot/order:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: order
              containerPort: 18084
              protocol: TCP
          resources:
            limits:
              memory: 512Mi
              cpu: '1'
          env:
            - name: PROFILE
              value: pro
            # 指定时区
            - name: TZ
              value: Asia/Shanghai
            - name: NACOS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: nacos
                  key: username
            - name: NACOS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nacos
                  key: password
            - name: NACOS_SERVER_ADDR
              valueFrom:
                configMapKeyRef:
                  name: nacos
                  key: serverAddr
            - name: NACOS_NAMESPACE
              valueFrom:
                configMapKeyRef:
                  name: nacos
                  key: namespace
            - name: NACOS_GROUP
              valueFrom:
                configMapKeyRef:
                  name: nacos
                  key: group
          volumeMounts:
            - name: order-log
              mountPath: /logs
      volumes:
        - name: order-log
          persistentVolumeClaim:
            claimName: order-log

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: order-log
  namespace: feng
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-storage