---
apiVersion: v1
kind: Service
metadata:
  name: sys
  namespace: feng
  labels:
    app: sys
spec:
  selector:
    app: sys
  ports:
    - name: http
      protocol: TCP
      port: 18080
      targetPort: 18080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sys
  namespace: feng
  labels:
    app: sys
spec:
  selector:
    matchLabels:
      app: sys
  revisionHistoryLimit: 10
  replicas: 1
  progressDeadlineSeconds: 300
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: sys
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: sys
          image: registry.cn-hangzhou.aliyuncs.com/f-boot/sys-service:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: sys
              containerPort: 18080
              protocol: TCP
          resources:
            limits:
              memory: 1024Mi
              cpu: '1'
          env:
            - name: PROFILE
              value: pro
            # 指定时区
            - name: TZ
              value: Asia/Shanghai
            - name: NACOS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: nacos
                  key: username
            - name: NACOS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nacos
                  key: password
            - name: NACOS_SERVER_ADDR
              valueFrom:
                configMapKeyRef:
                  name: nacos
                  key: serverAddr
            - name: NACOS_NAMESPACE
              valueFrom:
                configMapKeyRef:
                  name: nacos
                  key: namespace
            - name: NACOS_GROUP
              valueFrom:
                configMapKeyRef:
                  name: nacos
                  key: group
          volumeMounts:
            - name: sys-log
              mountPath: /logs
            - name: datetime
              mountPath: /etc/localtime
              readOnly: true
      volumes:
        - name: sys-log
          persistentVolumeClaim:
            claimName: sys-log
        - name: datetime
          hostPath:
            path: /etc/localtime

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sys-log
  namespace: feng
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-storage