apiVersion: v1
kind: ConfigMap
metadata:
  name: nacos
  namespace: feng
data:
  # 类属性键；每一个键都映射到一个简单的值
  serverAddr: nacos:8848
  namespace: pro
  group: f

immutable: true

#  # 类文件键
#  game.properties: |
#    enemy.types=aliens,monsters
#    player.maximum-lives=5
#  user-interface.properties: |
#    color.good=purple
#    color.bad=yellow
#    allow.textmode=true