#spring:
#  cloud:
#    sentinel:
#      datasource:
#        degrade:
#          nacos:
#            server-addr: 192.168.147.7:8848
#            namespace: dev
#            username: nacos
#            password: nacos
#            data-id: sentinel-degrade
#            group-id: DEFAULT_GROUP
#            data-type: json
#            rule-type: degrade
#        flow:
#          nacos:
#            server-addr: 192.168.147.7:8848
#            namespace: dev
#            username: nacos
#            password: nacos
#            data-id: sentinel-flow
#            group-id: DEFAULT_GROUP
#            data-type: json
#            rule-type: flow
#        system:
#          nacos:
#            server-addr: 192.168.147.7:8848
#            namespace: dev
#            username: nacos
#            password: nacos
#            data-id: sentinel-system
#            group-id: DEFAULT_GROUP
#            data-type: json
#            rule-type: system